import { useMemo, useState } from "react";
import Head from "next/head";
import { SubmitHandler } from "react-hook-form";
import { LayoutBikes, Header, FormSearch, BoxBike, Pagination } from "@components";
import { useBikes } from "@services";
import { locationEnum, FormFields } from "@types";
import { WrapperBikesInfo } from "../styles/styled";

const Home = () => {
  const [page, setPage] = useState(1);
  const [dataFilters, setDataFilters] = useState<Partial<FormFields>>({
    search: "",
    location: locationEnum.berlin
  });

  const { data, isLoading, error } = useBikes({
    query: dataFilters.search,
    location: dataFilters.location,
    stolenness: 'proximity',
    distance: 10,
    page,
    per_page: 10,
  });

  const bikes = data?.pages[0].bikes;

  const memoriesDataBikes = useMemo(() => {
    if (!bikes) {
      return [];
    }

    if (dataFilters && dataFilters.dateFrom && dataFilters.dateTo) {
      const startDate = new Date(dataFilters.dateFrom);
      const endDate = new Date(dataFilters.dateTo);

      return bikes.filter((bike) => {
        return (
          bike.date_stolen <= endDate.getTime() / 1000 &&
          bike.date_stolen >= startDate.getTime() / 1000
        );
      });
    }
    return bikes;
  }, [bikes, dataFilters]);

  const onSubmit: SubmitHandler<FormFields> = (dataRes) => {
    setDataFilters(dataRes);
  };

  if (error) return "Ha ocurrido un Error!!!";

  return (
    <>
      <Head>
        <title>Stolen Bikes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header city={dataFilters?.location} />

      <LayoutBikes>
        <FormSearch onSubmit={onSubmit} />

        {/* {!isLoading && <h2>Total: {data?.pages.}</h2>} */}

        <WrapperBikesInfo>
          {isLoading
            ? "...Loading..."
            : memoriesDataBikes.map((bike) => {
              // stolen_location  date_stolen
              const titleFull = `${bike.title} ${bike.frame_colors && `(${bike.frame_colors.join()})`} `
                return (
                  <BoxBike
                    key={bike.id}
                    description={bike.description ? bike.description : ""}
                    title={titleFull}
                    large_img={bike.large_img}
                    stolen_location={bike.stolen_location}
                    date_stolen={bike.date_stolen}
                  />
                );
              })}
        </WrapperBikesInfo>

        <Pagination page={page} setPage={setPage} />
      </LayoutBikes>
    </>
  );
};

export default Home;